/**
 * The 30 items the order requires in the public Notice, with the order's own titles and text:
 * Exchange Act Release No. 34-106402, §III "Information Included in the Public Notice"
 * (SEC PDF pp. 36–46; 91 FR 60177–81). Each item carries one source tag:
 *   chain          answered by live on-chain reads (program, venue, pools, mints)
 *   config         answered by the venue's own configuration (services/notice/venue.config.json)
 *   operator-input a narrative or legal statement only the operator can make; left empty and flagged
 */
export type ItemSource = "chain" | "config" | "operator-input"

export interface NoticeItemTemplate {
  letter: string
  title: string
  source: ItemSource
  /** The order's text for the item, verbatim. */
  requirement: string
}

const t = (letter: string, title: string, source: ItemSource, requirement: string): NoticeItemTemplate => ({ letter, title, source, requirement })

export const ORDER_CITE = "Exchange Act Release No. 34-106402, §III (91 FR 60177–81)"

export const NOTICE_ITEMS: readonly NoticeItemTemplate[] = [
  t("a", "Disclaimer", "config",
    "State that: (i) the TSV is not registered with the Commission in any capacity for the activities performed under the TSV Exemption and the Commission has not passed upon the merits or accuracy of the disclosures in the Notice; (ii) the TSV is not subject to the fair access requirements applicable to registered national securities exchanges and ATSs subject to Rule 301(b)(5) of Regulation ATS and that unfair and unreasonably discriminatory denials or limitations of access of TSV Participants by the TSV are not subject to SEC review; and (iii) the TSV is not subject to Regulation NMS."),
  t("b", "Use of the Exemption", "config",
    "The TSV must acknowledge that its use of the TSV Exemption is subject to Commission oversight and that operating a TSV in a manner inconsistent with the TSV Exemption could result in a Commission enforcement action."),
  t("c", "Overview of the Tokenized Securities Venue", "chain",
    "Describe generally the structure and organization of the TSV and its products, services, and operations. Describe the ownership and/or governance structure of the TSV, including both offchain and onchain governance mechanisms, and provide the name of any affiliated TSV. Include, as applicable, a description of any governance rights of LP tokens."),
  t("d", "Non-Exempt Activities", "operator-input",
    "Identify whether the organization, association, group of persons, or any person within a group that comprises the TSV is registered in any capacity with the Commission and, if so, provide a summary of the activities that require such registration with the Commission."),
  t("e", "TSV Participants", "config",
    "Describe the types of persons who are eligible to access and participate on the TSV (e.g., retail investors, institutional investors, liquidity providers, broker-dealers), including the types of persons that can access the TSV by way of a broker-dealer."),
  t("f", "Permission Trading Access Eligibility", "chain",
    "Describe the criteria or standards used to grant a person access to the services of the TSV. Describe the procedures for approving access (e.g., white-listing or permissioning) of potential TSV Participants or wallet addresses, including, among others, any procedures to verify a person's identity, and the procedures for providing access based on such approval. Describe any conditions or circumstances for denying or limiting a person from accessing TSV services, including for purposes of compliance with economic and trade sanctions programs administered by OFAC and applicable AML/CFT requirements."),
  t("g", "Securities, Non-Security Crypto Assets, and Tokenized Money Market Funds Traded", "chain",
    "Identify the Tokenized NMS Stocks and non-security crypto assets and tokenized money market funds that the TSV makes available for trading in pairs with Tokenized NMS Stock on the TSV. If applicable, indicate whether the TSV has paused trading in a Tokenized NMS Stock in connection with the limitations on the volume traded."),
  t("h", "Tokenization of Securities", "operator-input",
    "Describe the Tokenized NMS Stock traded, including whether they are tokenized by or on behalf of the issuers of the underlying NMS stock, or are tokenized by third parties unaffiliated with the issuers of the underlying NMS stock, and the processes used for tokenizing the Tokenized NMS Stock. Describe any procedures the TSV uses to evaluate the legal status, technical soundness, and operational integrity of each Tokenized NMS Stock it makes available for trading, and the distributed ledger system on which that security is issued and transferred."),
  t("i", "Tokenization", "operator-input",
    "Describe the steps (e.g., audits, certifications, attestations) the TSV has taken to verify that the Tokenized NMS Stock provides holders the same rights and privileges as does traditional NMS stock of an equivalent class."),
  t("j", "Notice of Issuer Objection", "chain",
    "Identify any issuer of an NMS stock underlying a Tokenized NMS Stock that has provided a timely Notice of Issuer Objection to trading the Tokenized NMS Stock."),
  t("k", "Tokenization by the TSV or its Affiliates", "operator-input",
    "State whether the organization, association, group of persons, or any person within a group of persons that comprises the TSV, the TSV's affiliates, or both, issued or tokenized any Tokenized NMS Stock that is made available for trading on the TSV and identify any such Tokenized NMS Stock. Describe any differences in treatment between Tokenized NMS Stock that is issued or tokenized by any such person and any other Tokenized NMS Stock made available for trading on the TSV."),
  t("l", "Trading Activities of the TSV and Its Affiliates", "config",
    "State whether the organization, association, group of persons, or any person within a group of persons that comprises the TSV, the TSV's affiliates, or both, can directly or indirectly display or enter trading interest on the TSV and, if so, state the capacity in which the TSV, its affiliates, or both, display or enter trading interest into the TSV as a TSV Participant (e.g., as a user or as a liquidity provider)."),
  t("m", "Differences in Treatment of TSV Participants", "config",
    "Describe any standards, policies, and procedures the TSV uses to differentiate among TSV Participants. Identify and describe any differences in treatment between or among TSV Participants (including any organization, association, group of persons, or any person within a group of persons that comprises the TSV and/or the TSV's affiliates that display or enter trading interest on the TSV). For example, identify and describe differences with respect to access, entry or display of trading interest, onchain or offchain trading procedures, market data, and fees."),
  t("n", "Distributed Ledger Technology", "chain",
    "Describe distributed ledger applications and networks of distributed ledger applications used by the TSV including the distributed ledger on which such applications are deployed and any cryptographic protocols employed to verify transactions on the distributed ledger; the smart contract addresses of distributed ledger applications; any use of protocols and applications (e.g., user interfaces, wallets, aggregators, solvers, relayers); and whether those protocols and applications are provided by the TSV, by related parties, or third parties, or a combination thereof. Explain whether the distributed ledger applications are interoperable with third-party service providers. Describe whether and how TSV Participants can access the TSV via custom integrations or direct interaction with smart contracts. Describe any circumstances under which the distributed ledger applications used by the TSV can be upgraded, modified, suspended, overridden, or ceased, the persons (whether unilaterally or in combination) that can upgrade, modify, suspend, override, or cease the distributed ledger applications used by the TSV, and the methods for upgrading, modifying, suspending, overriding, or ceasing the distributed ledger application. Provide the names of any entities and/or the roles of persons permitted to upgrade, modify, suspend, override, or cease each distributed ledger application."),
  t("o", "Entry of Trading Interest", "config",
    "Describe any procedures and functionality made available by the TSV for entering and interacting with trading interest in Tokenized NMS Stock and information solicited from TSV Participants (e.g., slippage tolerance, assets available to trade, price and quantity parameters). Describe the methods by which transactions are approved, confirmed, or verified on the relevant distributed ledger. In addition, describe procedures governing price and size parameters, including, but not limited to, minimum or maximum trade size, any daily trade limits, and any messages or flags provided to users."),
  t("p", "AMM Liquidity Pool Trading Procedures", "chain",
    "Describe any procedures for creating, modifying, accessing, and funding liquidity pools provided by the TSV. Describe procedures for purchasing and selling Tokenized NMS Stock using an AMM Liquidity Pool, including, among others, procedures governing the interaction among and between TSV Participants and trading in Tokenized NMS Stocks, including pricing, such as pricing models or curves (e.g., x * y = k), priority, ranking, order types, trading rules, allocation, and execution, as applicable. Describe any procedures for using any features that the TSV offers to allow liquidity pool customization; the applicability of the customization (e.g., the terms available to customize, including fees, and where in a trade's lifecycle it may be implemented); any permissioning required to use such customization features or customized liquidity pools; and procedures for addressing any requests made by users to alter or permit additional customizable settings."),
  t("q", "Offchain Trading Procedures", "config",
    "Describe any offchain functionality used by the TSV to facilitate trading on the TSV, how and where in the lifecycle of a trade such offchain functionality is used, and whether, and how, TSV Participants access the offchain functionality to support their use of the TSV."),
  t("r", "Hours of Operations", "config",
    "State the hours of operations of the TSV, including whether the TSV offers trading on a 24/7 basis."),
  t("s", "Use of Market Data", "config",
    "Describe whether, and if so, how, the TSV uses or integrates external market data, such as with oracles. Name any third-party service providers to the TSV for market data and describe the sources of any such market data. Describe the purposes of the market data (e.g., providing safeguards during periods of volatility or preventing manipulation) and how oracles are used by or on the TSV."),
  t("t", "Display", "config",
    "Describe any display of trading interest, including what is displayed, when it is displayed, whether it is displayed onchain or offchain, and how such displayed trading interest can be accessed. Describe any dissemination of information resulting from a transaction on the TSV, including what information is disseminated by whom, to whom, when, and how."),
  t("u", "Fees", "chain",
    "Describe the fee structure of the TSV, including any charges, fees, rebates and discounts and any other forms of compensation and the source of compensation, including whether (and if so, how much of) fees are shared with TSV Participants. Include or provide a link to any applicable fee or rebate schedule. Any relevant formulas or protocols used to determine and/or allocate fees are responsive. If fees or rebates are individually negotiated with TSV Participants or imposed in any other non-standardized manner (e.g., applying exceptions), describe the variables that impact the fees or rebates established."),
  t("v", "Complaints and Disputes", "operator-input",
    "Describe any procedures for resolving TSV Participant complaints and execution errors and disputes. If the TSV does not have these procedures, state so in the Notice."),
  t("w", "Procedures to Protect TSV Participant Information", "operator-input",
    "Describe any procedures and safeguards to protect the confidentiality of TSV Participants' information, including information that the TSV considers confidential, which can include any trading information on associated technology made available by the TSV (e.g., wallets). If the TSV does not have such procedures and safeguards, state so in the Notice. State whether the TSV will share TSV Participant confidential information and personally identifiable information (\"PII\") with other parties. Describe any policies and procedures designed to address Maximal Extractable Value (\"MEV\"). If the TSV does not have such policies and procedures, state so in the Notice."),
  t("x", "Systems Safeguards", "operator-input",
    "Describe any procedures related to the capacity, integrity, resiliency, availability, and security of the TSV, including any offchain or onchain systems, such as distributed ledger applications, used with the TSV. Such procedures include, but are not limited to: code review; the types of audits used (e.g., third-party audits, security audits, SOC 2 audits, code audits, incident audits, audits of distributed ledger applications, public auditability of the distributed ledger on which the distributed ledger applications are deployed); pre-trade risk assessments; post-deployment monitoring; authorization controls; stress tests; business continuity and disaster recovery plans testing; and any other contingency or incident response planning. If the TSV does not have such procedures, state so in the Notice. Identify the entity that performs each of the described functions."),
  t("y", "Clearing procedures and arrangements", "operator-input",
    "Describe any procedures or material arrangements undertaken to facilitate clearance and settlement of transactions on the TSV, including a description of any requirements applied to TSV Participants related to such procedures or material arrangements."),
  t("z", "Risks", "operator-input",
    "Describe any known material risks to TSV Participants or the integrity of the TSV's market, such as artificial intelligence exploits or attacks, loss of private keys, compromised wallets, smart contract coding errors or bugs, access control failures, reentrancy attacks, denial-of-service attacks, congestion, impermanent loss, any abusive activity involving MEV (e.g., front-running, back-running, sandwich attacks), oracle manipulation, network cyber-attacks, or phishing attacks. Explain any actions the TSV takes to mitigate the risks and compensate for any losses."),
  t("aa", "Service Providers", "operator-input",
    "Identify any entities, other than the TSV, that support the services or functionalities of the TSV and describe their roles and responsibilities with respect to the TSV. These include, among others, service providers that perform services related to permissioning subscribers, identifying and mitigating cyber risk, monitoring trading activity, displaying trading interest, recordkeeping, and clearance and settlement."),
  t("bb", "Trading Oversight", "operator-input",
    "Describe any monitoring by the TSV to detect fraudulent or manipulative trading activity (e.g., spoofing, wash trading, front running, pump-and-dump schemes), illegal trading of Tokenized NMS Stock, and other market abuses occurring on the TSV. If the TSV does not perform such monitoring, state that in the Notice."),
  t("cc", "Stoppage of Trading", "config",
    "Describe the circumstances under which the TSV would stop trading or displaying trading interest (e.g., a trading halt in the underlying NMS stock in the event a market-wide circuit breaker is triggered or pending dissemination of material news, a trading suspension of the underlying NMS stock associated with delisting proceedings or by the SEC, or a TSV-initiated stoppage upon approaching the volume threshold). Describe any risk controls, including any circuit breakers or reference price bands, and any procedures to address price volatility or trading involving, for example, corporate actions occurring when markets for the underlying securities are closed. Describe the circumstances and procedures for resuming trading, accepting trading interest, or displaying trading interest after a stoppage."),
  t("dd", "Exclusive or Predominant Venue for Trading of a Tokenized NMS Stock", "operator-input",
    "Describe whether the TSV may be the exclusive or predominant trading venue for a Tokenized NMS Stock (e.g., a Tokenized NMS Stock is encoded to trade exclusively on the TSV), and if so, describe any potential risks to TSV Participants associated with the TSV being the exclusive or predominant trading venue for a Tokenized NMS Stock. For example, such risks may include TSV Participants being unable to trade the Tokenized NMS Stock on another trading venue, which may subject TSV Participants to having no choice other than accepting the terms and conditions, including fees, of the exclusive or predominant TSV to trade that Tokenized NMS Stock. Describe any procedures to address such risks, such as, for example, processes to burn or detokenize the Tokenized NMS Stock."),
]
